### ISSUE TITLE
Feature request: Give commands a name or label

### ISSUE THREAD

**Issue by seriema** [yamajyn/commandlist#18]
This is a great extension! I no longer need to keep snippets in temporary files. What would be really useful would be to give the command a descriptive name. Right now the name is the actual command, and bash commands can easily become too hard to read what the full command will do.

Here are some examples:

* "CPU architecture": `uname -m`
* "List installed packages": `apt list --installed | sed 's:/[^/]*$::'`
* "Install nano": `sudo apt-get update && apt-get install -y nano`
* "Is the directory empty?": `[ -z "``find $PWD -maxdepth 3 -type f``" ] && echo "Directory is empty" || echo "Directory is not empty"`

**Comment by yamajyn** [comment]
Thanks for your feedback! I also think so. I actually tried it during development. However, I thought about the risk of executing unintended commands, so I put it off. Please wait a little! I'll try.
