### ISSUE TITLE
Extension is broken

### ISSUE THREAD

**Issue by amcdonagh-unipart** [yamajyn/commandlist#27]
Nothing works anymore, I think due to a new version of vscode. When I click any icon, it raises `command 'globalCommandExplorer.sync' not found`. All commands have disappeared as well.
![Screenshot from 2021-05-10 12-50-29](https://user-images.githubusercontent.com/78161607/117654936-54233d00-b18e-11eb-9fa1-0fee5e4913c3.png)

**Comment by PyDataBlog** [comment]
Any news on this?

**Comment by yamajyn** [comment]
I checked the fix in the latest version. If not fixed this issue, please reopen.

**Comment by PyDataBlog** [comment]
Is the fix in the extension now? I just installed and it's the same issue?

**Comment by PyDataBlog** [comment]
> I checked the fix in the latest version. If not fixed this issue, please reopen.

Is the fix in the extension now? I just installed and it's the same issue?

**Comment by yamajyn** [comment]
thx, please make new issue here.
https://github.com/yamajyn/commandlist/issues/new?assignees=&labels=bug&template=bug_report.md
